"""add timezone to users and businesses

Revision ID: 774be5dfe273
Revises: a67c11d731c9
Create Date: 2026-09-22 06:41:59.776988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '774be5dfe273'
down_revision: Union[str, None] = 'a67c11d731c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('timezone', sa.String(length=64), server_default='UTC', nullable=False))
    op.add_column('users', sa.Column('timezone', sa.String(length=64), server_default='UTC', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'timezone')
    op.drop_column('businesses', 'timezone')
    # ### end Alembic commands ###
